Algoritmo "variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : JOnatha Lima
// Data atual  : 19/09/2021
Var
// Seção de Declarações das variáveis 
   nota: inteiro,
   nota2: real,
   nome: caractere,
   passou: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo